agent {
    data_dir = "/opt/spire/data/agent"
    log_level = "DEBUG"
    server_address = "spire-server"
    server_port = "8081"
    trust_domain = "example.org"
    trust_bundle_path = "/certs/spire-root-ca.crt"
}

plugins {
    NodeAttestor "x509pop" {
        plugin_data {
            # Fingerprint 472bf65da853e3fd53c47e78ec1b12e9e904741c
            private_key_path = "/certs/spire-agent.key"
            certificate_path = "/certs/spire-agent.crt"
        }
    }

    KeyManager "memory" {
        plugin_data {}
    }

    WorkloadAttestor "unix" {
        plugin_data {
            discover_workload_path = true
        }
    }
}

health_checks {
    listener_enabled = true
    bind_address = "0.0.0.0"
    bind_port = "8080"
    live_path = "/live"
    ready_path = "/ready"
}
