# GSSAPI options
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
GSSAPIStrictAcceptorCheck yes
GSSAPIKeyExchange yes

# Fetch S4U tickets for admin
Match user admin
    GSSAPIAllowS4U2Self 5m
    GSSAPIProxyS4U2Services HTTP/ipa.example.org

LogLevel DEBUG2
