# GSSAPI options
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
GSSAPIStrictAcceptorCheck yes
GSSAPIKeyExchange yes
#GSSAPIEnablek5users no

Match user admin
    GSSAPIAllowS4U2Self 5m
    GSSAPIProxyS4U2Services HTTP/ipa.example.org

# Enable pubkey auth
# PubkeyAuthentication yes
# AuthorizedKeysCommand /usr/bin/sss_ssh_authorizedkeys
# AuthorizedKeysCommandUser nobody
# LogLevel DEBUG2
