[sssd]
services = nss, pam, ifp, ssh, sudo
domains = example.org

[domain/example.org]
ipa_server_mode = True
id_provider = ipa
ipa_server = ipa.example.org
ipa_domain = example.org
ipa_hostname = ipa.example.org
krb5_realm = EXAMPLE.ORG
ldap_tls_cacert = /etc/ipa/ca.crt

[pam]
pam_gssapi_services = sudo, sudo-i
